---
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################
#######################         Jobs below are used to build only             #########################################
#######################        master  branches for all containers            #########################################
#######################                                                       #########################################
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

# 1/2 This pipeline would be used after each merge request  to build ml_all:latest docker image
kind: pipeline
type: docker
name: mmdetecion LS_mmdet_latest

platform:
  arch: amd64
  os: linux

trigger:
  branch:
    - main
  event:
    - push

clone:
  depth: 1

steps:
  - name: Build latest mmdetecion LS_mmdet_latest docker image
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      dockerfile: docker/Dockerfile
      context: docker/
      registry: quay.io
      repo: quay.io/logivations/mmdetecion
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from: quay.io/logivations/mmdetecion:LS_mmdet_latest
      tags:
        - LS_mmdet_latest
        - LS_mmdet_latest_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD


#######################################################################################################################
#######################################################################################################################
#######################################################################################################################
#######################              Jobs below are used to run               #########################################
#######################             pull request validation only              #########################################
#######################                                                       #########################################
#######################################################################################################################
#######################################################################################################################
#######################################################################################################################

---
## 1. Pre-commit validation before start docker build
# kind: pipeline
# type: docker
# name: PR validation pre-commit check

# platform:
#   arch: amd64
#   os: linux

# clone:
#   disable: true

# trigger:
#   event:
#     include:
#       - pull_request

# image_pull_secrets:
#   - dockerconfig_prd

# steps:
#   - name: Pre-commit validation
#     image: 
#     pull: always
#     commands:
#       - git clone --depth 1 ${DRONE_GIT_HTTP_URL} -b ${DRONE_SOURCE_BRANCH}
#       - cd mmdetecion && git fetch --depth 1 origin ${DRONE_TARGET_BRANCH} && git diff --name-only FETCH_HEAD | xargs pre-commit run --files


# 2. Build docker image for mmdetection
---
kind: pipeline
type: docker
name: PR validation build mmdetecion images

platform:
  arch: arm64
  os: linux

trigger:
  event:
    include:
      - pull_request

# depends_on:
#   - PR validation pre-commit check

clone: 
  depth: 50

steps:
  - name: Build LS_mmdet docker image for pull request
    image: plugins/docker:20.14
    environment:
      DOCKER_BUILDKIT: 1
    settings: 
      dockerfile: docker/Dockerfile
      context: docker/
      registry: quay.io
      repo: quay.io/logivations/mmdetecion
      privileged: true
      build_args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from: 
        - quay.io/logivations/mmdetecion:LS_mmdet_latest
        - quay.io/logivations/mmdetecion:LS_mmdet_pr${DRONE_PULL_REQUEST}
      tags:
        - LS_mmdet_pr${DRONE_PULL_REQUEST}
        - LS_mmdet_pr${DRONE_PULL_REQUEST}_${DRONE_COMMIT_SHA}
      username:
        from_secret: DOCKER_QUAY_USERNAME
      password:
        from_secret: DOCKER_QUAY_PASSWORD